INSERT INTO merchant_aliases (alias, merchant)
VALUES ('RSP*SWIGGY', 'Swiggy'),
    ('WWW SWIGGY COM', 'Swiggy'),
    ('Swiggy IN', 'Swiggy'),
    ('SPOTIFY', 'Spotify'),
    ('RSP*NYKAA VIA SMARTBUY', 'Nykaa'),
    ('AIRTEL PAYM', 'Airtel Pay'),
    ('RetailCCA', 'Steam'),
    ('YOUTUBE CYB', 'YouTube'),
    ('YOUTUBE', 'YouTube'),
    ('Raz*Swiggy Technologie', 'Swiggy'),
    ('AMAZON PAY INDIA PRIVA', 'Amazon'),
    ('SWIGGY', 'Swiggy'),
    ('SWIGGY LIMITED', 'Swiggy'),
    ('PPSL*SWIGGY', 'Swiggy'),
    ('Innovative', 'Big Basket');